### ISSUE TITLE
Romanji is defaulting even if English title selected.

### ISSUE THREAD

**Issue by icpryde** [SwagOtaku/plugin.video.kaito#10]
I'm not sure if this is a bug but you introduced showing either Romanji or English titles, so when I make it english...this is what I see still?

![Screen Shot 2020-10-25 at 6 45 05 PM](https://user-images.githubusercontent.com/29389746/97121252-3b23d480-16f3-11eb-915f-a9ee932cd908.png)

Still seems like its showing Romanji over English...at least for the title with the show as you can see at the top.

![Screen Shot 2020-10-25 at 6 53 39 PM](https://user-images.githubusercontent.com/29389746/97121275-66a6bf00-16f3-11eb-8908-9f897b4adec4.png)

**Comment by icpryde** [comment]
Or was this the way it always was?

**Comment by icpryde** [comment]
I updated to 0.0.6, not sure if titles are still working as intended in english? As seen here it's still showing romanji but the episode titles are in english but the titles of the show still happen to be romanji?

![Screen Shot 2020-11-27 at 9 27 42 PM](https://user-images.githubusercontent.com/29389746/100492114-64bb8b80-30f7-11eb-97dd-3460e84f6855.png)

**Comment by SwagOtaku** [comment]
@icpryde rebuild database in tools.

**Comment by icpryde** [comment]
@SwagOtaku after rebuilding the database, clearing cache and restarting kodi the names still show up in romanji as listed above.

**Comment by icpryde** [comment]
I'm going to close this to start a new request with updated information.
