### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by jaimsitecom** [SwagOtaku/plugin.video.kaito#105]
Nothing comes up when searching /scrape. 

No more update and support for kaito?  This is sad.

**Comment by ahmedashed** [comment]
It is still currently working for me, make sure all the usual have the latest update and so on. 

I am using real debrid and for added convenience I just add whatever should I am watching to the cloud. Allow cloud scraping in the account section of the settings then enjoy the show.

**Comment by jaimsitecom** [comment]
> It is still currently working for me, make sure all the usual have the latest update and so on.
> 
> I am using real debrid and for added convenience I just add whatever should I am watching to the cloud. Allow cloud scraping in the account section of the settings then enjoy the show.

Wow. You are lucky. Mine wont work anymore. I uninstalled and reinstalled already. Setup my debrid too but still no joy. I wonder if it’s because i updated Kodi to 19.4. Itms the only reason i think that broke Kaito. Whenever i open folders inside Kaito, a kodi error comes up. 😞 

i hope Swag or another developer comes back and fixes this. It’s such a great app until it broke. Sigh

**Comment by ahmedashed** [comment]
That's very strange, I am also on 19.4. I wonder what could be causing it. I wouldn't bother using any other functions besides searching for the anime you want and the latest folder. All the rest are outdated or not working. I even managed to get my MAL account authenticated to access my playlist so that works. I should also mention I'm using 0.10 or basically not the beta on this github so that could be something you can try. Maybe it's the debrid if it's different?

**Comment by jaimsitecom** [comment]
> That's very strange, I am also on 19.4. I wonder what could be causing it. I wouldn't bother using any other functions besides searching for the anime you want and the latest folder. All the rest are outdated or not working. I even managed to get my MAL account authenticated to access my playlist so that works. I should also mention I'm using 0.10 or basically not the beta on this github so that could be something you can try. Maybe it's the debrid if it's different?

Hey thanks for your tips. I’ll try all your suggestions.

**Comment by jaimsitecom** [comment]
No joy. When it starts to scrape for a show, it only uses NYAA, CLOUD INSPECTION and GOGO. Before it has a lot more providers as options but now only thos three come up. I wonder why it won’t search from other providers. I already activated both my REALDEBRID and ALLDEBRID accounts. So frustrating.

**Comment by ahmedashed** [comment]
Ah that sounds like it is working as intended if it still is not finding the anime, use an addon like realizer which lets you play files from your cloud. If you set up auto play in your settings or click play from here it will auto play files in an order. It is a pain there isn't an anime addon that rules them all.

**Comment by jaimsitecom** [comment]
Used realizer. It worked for some anime titles but kinda choosy. I find it hassle/extra work to use 2 addons just to watch an anime title that might work or not. 

I guess i’ll give up on Kaito (for now). I installed Gogo Anime and WatchNixtoons2. They’re both ok and straightforward to use. 

Hey thanks again for all the  help, unfortunately it didn’t work out to make Kaito work like the early days. 

Take care man.

**Comment by Deadshot9669** [comment]
> That's very strange, I am also on 19.4. I wonder what could be causing it. I wouldn't bother using any other functions besides searching for the anime you want and the latest folder. All the rest are outdated or not working. I even managed to get my MAL account authenticated to access my playlist so that works. I should also mention I'm using 0.10 or basically not the beta on this github so that could be something you can try. Maybe it's the debrid if it's different?

Hi everyone, I have Kodi 19.4 (with LibreeLec 10.0.2) too but I always receive an error when I try to play something: I checked the log and seemed to be a Python version error ("JSONDecodeError"). 
So my question is: wich version of python have you installed on your system? Mine is 3.8

**Comment by Goldenfreddy0703** [comment]
Hey guys, sorry i never replied but katio is not dead, sure the dev is kinda dead but im helping maintain it. 
If you guys would like to try the new beta me and jkaw released, here is a link to help you guys out. 

https://github.com/Goldenfreddy0703/plugin.video.kaito.beta

# Installation & Updates

_You can install it via repository to provide automatic updates_

- Download repository: [repository.hooty](https://github.com/Goldenfreddy0703/repository.hooty/blob/master/repo/zips/repository.hooty/repository.hooty-1.0.zip)
- Or install it via Kodi file-manager
  - add source: https://goldenfreddy0703.github.io/repository.hooty

_or install it manually (updates should be installed manually)_

- [plugin.video.kaito.beta](https://github.com/Goldenfreddy0703/plugin.video.kaito.beta/archive/refs/heads/main.zip)

**Comment by jaimsitecom** [comment]
I installed your version and it didnt get anymore error like the ver.  10-matrix. Only problem i get is that whenever i choose a anime show i want to watch it wont search on other providers. It will only ahow up 3 (NYAA, GOGO and Cloud Inspection). Why is that?  A couple months ago it would search on torrent or file sharing providers but now only 3 show up and it won’t get any files from them so I don’t get to watch anything anymore. 

Thanks for continuing this ‘used to be’ great addon but hopefully i get to resolve the problem i get on it. 

![4E909403-7F29-411C-8C9E-F72AEE897D6E](https://user-images.githubusercontent.com/58242813/166890061-b4a5ad43-8120-4501-adc1-85f10744c0eb.jpeg)

**Comment by ahmedashed** [comment]
To be honest I don't remember it ever searching other providers besides those three, maybe you were using another addon? Like seren, venom, the crew, etc

**Comment by ahmedashed** [comment]
> Hey guys, sorry i never replied but katio is not dead, sure the dev is kinda dead but im helping maintain it. If you guys would like to try the new beta me and jkaw released, here is a link to help you guys out.
> 
> https://github.com/Goldenfreddy0703/plugin.video.kaito.beta
> 
> # Installation & Updates
> _You can install it via repository to provide automatic updates_
> 
> * Download repository: [repository.hooty](https://github.com/Goldenfreddy0703/repository.hooty/blob/master/repo/zips/repository.hooty/repository.hooty-1.0.zip)
> * Or install it via Kodi file-manager
>   
>   * add source: https://goldenfreddy0703.github.io/repository.hooty
> 
> _or install it manually (updates should be installed manually)_
> 
> * [plugin.video.kaito.beta](https://github.com/Goldenfreddy0703/plugin.video.kaito.beta/archive/refs/heads/main.zip)

You should post this on reddit if you haven't done so already :)

**Comment by jaimsitecom** [comment]
Oh I’m pretty sure it scraped other providers like rapid, and other file servers. Besides nyaa, gogo, the notification gets quite full with 4 to 5 more providers besides these 3.

**Comment by tehandeh** [comment]
Did you activate whatever debrid account you have in settings?

**Comment by jaimsitecom** [comment]
> Did you activate whatever debrid account you have in settings?
> […](#)

Yes i did. No difference.

**Comment by Goldenfreddy0703** [comment]
Ummm hi, I received a notification on this issue page, if you guys need a good anime addon, try Otaku lol. 

https://github.com/Goldenfreddy0703/Otaku
