### ISSUE TITLE
Can't play off All Debrid

### ISSUE THREAD

**Issue by TaiDak** [SwagOtaku/plugin.video.kaito#11]
First, great addon, the two best things about it are of course the ability to use debrids, and almost all anime have name, info, and correct thumb for the episode. 

The problem for me is that Kaito can't play anything from All Debrid. Real Debrid and the embeds play fine. All Debrid shows me the links, even the pack ones, but when I press on them nothing happens, not even an error notification.

Btw, Real Debrid show the links, but not the pack ones unless I rescrape.

Third thing, more of a Artic Horizon compatibility, if it's possible to add an option for content types for each section, meaning the menu, the animes, and the episodes, if possible, instead of just the menu. Another one is that the Next Up menu in kitsu displays the episodes as posters, and if you set it up as landscape, it displays the background fanart instead of the episode thumbnail, which some of the animes do have. 

I understand about the last section of my rant not being a priority, since it's mostly just appearance. 

Btw here's my log
http://paste.kodi.tv/wegaragaya

**Comment by G-streamer** [comment]
I don't know if this is the problem, but I was looking for a command shortcut to authorize RD directly from a super-favourite menu option and noticed an error in the default.py. It authorizes RD instead of AD.
@route('authRealDebrid')
def authAllDebrid(payload, params):
    from resources.lib.debrid.real_debrid import RealDebrid
    RealDebrid().auth()

**Comment by SwagOtaku** [comment]
@TaiDak I think All Debrid changed up its api, so that's why All Debrid isn't working. I need an account to get it working again

**Comment by TaiDak** [comment]
I think they let you try it out for 7 days, unless those 7 days aren't enough to fix the problems

**Comment by SwagOtaku** [comment]
I've already used the 7 day trial when I initially added all debrid support

**Comment by TaiDak** [comment]
Issue still persists, but I switched to real debrid so it doesn't matter to me anymore
