### ISSUE TITLE
Error trying to watch movies

### ISSUE THREAD

**Issue by icpryde** [SwagOtaku/plugin.video.kaito#12]
Hey @SwagOtaku 

I noticed a bug I was trying to watch My Hero Academia: Heroes Rising but I just get an error message, I checked nyaa and it's listed there.

Log file:
https://paste.ubuntu.com/p/c8b3WM9Fp4/

**Comment by icpryde** [comment]
After further testing it seems it’s movie files that don’t work in general. I tested a bunch of new and old movies all listed on nyaa and none of them work.

**Comment by icpryde** [comment]
Hey @SwagOtaku thanks for the update, i was testing it out not sure what you fixed for improved scraping but I tested some movies after the update and still none of them are working I get this error.

![Screen Shot 2020-11-27 at 9 07 50 PM](https://user-images.githubusercontent.com/29389746/100491822-be6e8680-30f4-11eb-86de-8f56f2511ce2.png)

**Comment by SwagOtaku** [comment]
@icpryde try clearing cache and rebuilding database in tools.

**Comment by icpryde** [comment]
@SwagOtaku I tried clearing cache, I rebuilt the database and restarted kodi and still the same issue.

![Screen Shot 2020-12-01 at 5 44 16 PM](https://user-images.githubusercontent.com/29389746/100805868-6ccc4180-33fd-11eb-907c-b75f3fec8106.png)

Arctic Horizons is a pretty standard kodi skin that a lot of people use.

**Comment by icpryde** [comment]
I switched skins to the default kodi skin to see if that made a difference and I still received the same error, i even attempted another rebuild and clear cache.

**Comment by icpryde** [comment]
I'm going to close this and make a new one with updated information.
