### ISSUE TITLE
Movies are not working at all

### ISSUE THREAD

**Issue by icpryde** [SwagOtaku/plugin.video.kaito#23]
I've tried many times, I've cleared cache and rebuild database but the movie files do not work at all and I always get an error as seen here.

![Screen Shot 2020-12-23 at 4 12 47 PM](https://user-images.githubusercontent.com/29389746/103038771-49e50700-453d-11eb-9f26-225184cc856e.png)

I have attached a small video as well:
https://streamable.com/6aqvaw

Here is the log file:
https://paste.ubuntu.com/p/XYDwd8phtd/

Uploaded log incase above link is expired:
[logfile.txt](https://github.com/SwagOtaku/plugin.video.kaito/files/5737207/logfile.txt)

**Comment by SwagOtaku** [comment]
@icpryde i adjusted rebuild database that should fix the issue because it seems like the previous rebuild database was hit or miss with different devices, but this should hopefully rebuild the database for you now. Let me know how it goes

**Comment by icpryde** [comment]
@SwagOtaku So i'm testing this on windows PC and after the update and clicking rebuild database, it seems like nothing is really happening unless the rebuild is super fast but I get no confirmation it's complete. I just get the initial question asking "this will reset all meta inforomation"

![Screen Shot 2021-01-02 at 8 06 07 PM](https://user-images.githubusercontent.com/29389746/103469693-fee5a380-4d35-11eb-9c4e-e59689300cfd.png)

I've tried, clearing cache, restarting kodi and attempted rebuild database again but nothing happens? I went ahead and clicked on a movie again with the same error occurring. 

![Screen Shot 2021-01-02 at 8 05 11 PM](https://user-images.githubusercontent.com/29389746/103469675-d5c51300-4d35-11eb-87a8-cbf8533c7326.png)

So unfortunately, still no luck :(

**Comment by icpryde** [comment]
@SwagOtaku Ok so i've been digging around some more and I think I know why its not working, It's not the skin i've confirmed with others that are also using Artic Horizon skin that they can get the movies to work. So it comes down to 2 factors then either its an issue with using AniList instead of MAL as the person I confirmed with was using MAL.

Though more realistic I think its a Real Debrid vs Premiumize issue, I'm using PM and this person was using RD that seems to be the only real difference so I think however PM is grabbing or trying to grab the movie file it then can't seem to play it for whatever reason.

Have you tried playing movie files with PM?

So either its its a combination of AniList + PM making movies not work or its just PM this im not totally sure on but I think this is why the movies dont work.

I've attempted a clean install with only Kaito using my AniList and PM set up and it still won't work and I get the same above errors so I think this is the issue.

**Comment by SwagOtaku** [comment]
@icpryde The new update (version 0.0.8) should fix this issue.
Movies were working in the addon, it was just when you tried to access the movies via AniList watchlist that the errors occurred.

**Comment by icpryde** [comment]
@SwagOtaku  I can confirm movies are working now, this is fantastic :) the only thing I noticed its a minor thing. It now brings up the different torrent links instead of auto playing the first source. I have it set to "auto play" but this happens and it only happens when playing a movie not a series.

none the less this is a super minor thing but just bringing it to your attention its not detecting that I have it set to "auto play".

![Screen Shot 2021-01-25 at 8 09 03 PM](https://user-images.githubusercontent.com/29389746/105785727-9612d500-5f49-11eb-947f-db5aacf4fda6.png)

**Comment by icpryde** [comment]
@SwagOtaku one other small thing, when you play the movie from a widget it doesn't grab the data to tell you what movie is playing etc when you pause as you see here.

![Screen Shot 2021-01-27 at 8 50 07 AM](https://user-images.githubusercontent.com/29389746/106000295-ab3c5080-607c-11eb-85a7-bfa264308e34.png)

This is what it should show as an example:

![Screen Shot 2021-01-27 at 8 52 04 AM](https://user-images.githubusercontent.com/29389746/106000614-040be900-607d-11eb-9ca7-89dd96c92169.png)
