### ISSUE TITLE
PSA: Don't use Auto Play. Use Source Select.

### ISSUE THREAD

**Issue by DaisyF8** [SwagOtaku/plugin.video.kaito#26]
For embedded source in my experience only the second result will start, and only on the second attempt.

For cached sources, I often need to click the source a second time, the first time returns me to the results screen.

Or it will trigger the search again. And you then need to select your source again.

On Autoplay this is hidden and confusing. Be aware of what's happening and use Source Select.

**Comment by SwagOtaku** [comment]
version 0.0.7 should fix this, the gogo embed needed to be updated that's what was causing the autoplay to get messed up when you got to gogo embed

**Comment by DaisyF8** [comment]
Thx.
