### ISSUE TITLE
PSA: no cached sources found ? Upload a magnet to Debrid or Premiumize yourself.

### ISSUE THREAD

**Issue by DaisyF8** [SwagOtaku/plugin.video.kaito#27]
If you don't see cached results, there probably aren't any yet. Find the magnet you want and upload it. As soon as it is downloaded Kaito will find it.

**Comment by sathish804** [comment]
It seems Debrid scrapping is broken in Kaito. I also don't see any cached sources for Naruto even though there are cached sources in RD and in my RD cloud as well.

**Comment by SwagOtaku** [comment]
I have an update with improving cloud inspection ready to release, but as i'm writing this trakt is having issues. So i'm holding out releasing until trakt stabilizes.

**Comment by DaisyF8** [comment]
Awesome 😄

**Comment by sathish804** [comment]
> I have an update with improving cloud inspection ready to release, but as i'm writing this trakt is having issues. So i'm holding out releasing until trakt stabilizes.

Great to know!! Thank You!!

**Comment by icpryde** [comment]
@SwagOtaku ya trakt was having issues and then Seren just released its huge 2.0 update so tons of database rebuilding utilizing trakt which brought it down again lol. Though it seems things are stable now <3

**Comment by icpryde** [comment]
Also completely agree with @DaisyF8 simply cache the anime yourself to your RD or PM account, this actually helps all of us in the long run as more anime will be available on there meaning more available for all of us to watch.
