### ISSUE TITLE
New episodes not being added

### ISSUE THREAD

**Issue by RayZorJ3lade** [SwagOtaku/plugin.video.kaito#31]
Hi, kaito is absolute anime nirvana! Thankyou 👍 
But for a few weeks now I'm not getting new episodes added to series' - specifically Mahouka Koukou no Rettousei: Raihousha-hen
Latest episode on the addon is Ep11 but we're now up to episode 13

Can someone confirm if they see the same?

Also I'm using the Arctic Zephyr 2 skin and the movie db helper so it is possible that is interfering

**Comment by SwagOtaku** [comment]
thanks for the catch, fixed in version 0.0.7
