### ISSUE TITLE
Arctic Horizon skin

### ISSUE THREAD

**Issue by vidje** [SwagOtaku/plugin.video.kaito#35]
Hello, the plugin works with estuary skin, but when I open it in arctic horizon it just gives me blank page for some reason. Looks like on the preview below. Any ideas?
![preview](https://user-images.githubusercontent.com/857160/104013075-3b3f5680-51b1-11eb-9554-d0c3418d94f3.png)

**Comment by TaiDak** [comment]
Something about content types, i don't know the specifics details. Simply go to the addon settings and check the set content types box, and set the menu content type to episodes or tv show, exit kodi, I'd refresh the skin, and then go back into the addon. You can change it to whatever you want again, like add-ons, and it's still open, just go to do it once

**Comment by vidje** [comment]
> Something about content types, i don't know the specifics details. Simply go to the addon settings and check the set content types box, and set the menu content type to episodes or tv show, exit kodi, I'd refresh the skin, and then go back into the addon. You can change it to whatever you want again, like add-ons, and it's still open, just go to do it once

The add-on works now. Is there something like Arctic Horizon skin for the add-on itself, like there is for Seren?

**Comment by quincyp** [comment]
> Something about content types, i don't know the specifics details. Simply go to the addon settings and check the set content types box, and set the menu content type to episodes or tv show, exit kodi, I'd refresh the skin, and then go back into the addon. You can change it to whatever you want again, like add-ons, and it's still open, just go to do it once

This fixed it for me as well, for reference on the Eminence skin.

**Comment by SwagOtaku** [comment]
> Is there something like Arctic Horizon skin for the add-on itself, like there is for Seren?
@vidje Currently no
