### ISSUE TITLE
Tracking and seasons

### ISSUE THREAD

**Issue by TaiDak** [SwagOtaku/plugin.video.kaito#36]
This is is issue an with how kaito uses trakt/tmdb for episode metadata. This isn't compatible with some anime, some specific examples being attack on titan season 3, haikyuu to the top, and re zero season 2. What happens is that trakt/tmdb doesn't see that these anime are divided into two parts. For example, if I wanted to watch episode 1 of attack on titan season 3 part 2, 

I would have to first search it on kaito, and 

then select attack on titan season 3 part 2. 

Now here's where it gets complicated, because instead of displaying the episodes for part 2, kaito will display the episodes from both part 1 and part 2, it will treat both parts as a single season. But because kaito is using the name of anime and not the name of the episode to scrape the files, you can't just go the the actual first episode of part 2, which is season 3 episode 14 according to kaito. You have the play episode 1 for it to find the right episode. This isn't a huge problem, since if you're using a tracker like mal or kitsu, if you were able to actually play episode 14, kitsu wouldn't track it correctly. It would only be a visual problem.

Now here's something even more wack. The opposite thing actually happens with re zero season 2. Kaito can't scrape anything for re zero season 2 part 2, and you'd think you can just go to the regular re zero season 2 and just play episode 14, but it also can't find it. Instead, in order to play the correct episode, you have to go to re zero, the first season, select season correction, and the select season 2, and then play episode 14. Of course this isn't really a problem if you don't use any trackers, but if you do, what will happen is that anilist or mal or kitsu will think you're on episode 14, of the first season. You're not tracking what you're actually watching

That's all I wanted to say, and I do apologise for my long post.

**Comment by DaisyF8** [comment]
I didn't notice your post when it was open.  You give a good description of the kind of stuff that's involved to make things work (exact).

Don't know if this can get fixed. The mere fact that Kaito works for 90% of the time how I use it is amazing. It searches Nyaa. It uses Debrid 😁

Thanks for your write-up. Maybe it can be a guide for the dev. Awesome that you gave examples 👍

**Comment by TaiDak** [comment]
I was half asleep when I wrote that lol, and after further playing around with stuff, I discovered some stuff I said is wrong.


[The following was done using Premiumize, since their cloud storage is far superior to Real-Debrid, because Premiumize allows me to rename the folders and files, delete, and move in any way I want]

Kaito does scrape for episodes. Although I don't completely understand the process, kaito will find any cached torrent as long as it's title somewhat resemble each other. For single episodes, an example would be "Spice and Wolf S01E01". As long as "Spice" is in the cached torrent file name, kaito will correctly match it with Spice and Wolf. Trying it with just "Wolf" won't give the same result for some reason, but if I use either ookami or koushinryou, either separate and together, kaito will find it. 
Kaito works a little different for batches, instead it will first look for the the title of the root folder, and then, inside for the episode. It's kind of hard to explain, but, kaito will only find episodes of batch cached torrents only if the episodes inside the folder are on the root of the folder, not inside another folder, and if the episode file name also have the following characters, which can be either : Episode01, E01, -01, _01, (01. The characters Episode, E, -, _, and (, always have to be infront of the 01, with 01 representing the episode number, kaito will not find the episode of it's written without 2 digits, the episode number cannot be a single digit, hence 01 for episode 1, 02 for episode 2, and so on, the minimum must be 2 digits. Kaito also will not find the episode even if it's 01 by itself, either the word Episode, the letter E, or the symbols -, _, or (, must be in front of the episode number.

Therefore check when adding torrents to your cloud storage that the episode names have -, _, (, episode, or e in front of the episode number, and that the episode number must be written with a minium of two digits. Also the episodes must be in the root of the folder, not inside another folder.


Now going back to trakt, kitsu, and seasons, I managed to find a way for kaito to correctly scrape episodes for animes with a part 2. Example of re zero s2 part 2, kaito cannot find the cached episodes, it only finds them if you go to re zero season 1, and use season correction to turn it into season 2, and even them, you have to guess what episode, because some torrent release groups are going naming the episodes in part 2 from episode 1, and others from episode 14. Because kaito uses trakt/tmdb for episode data, it combines part 1 and part 2. In order for kaito to find the episode, you have to manually add it to your cloud storage in your debrid account, but for example you want to see the episode 1 of re zero s2 part 2, you have to find a torrent whose file name has a 14 in it, since according to trakt/tmdb, part 2 doesn't exist, even though according most release groups, episode 14 is actually just the episode 01 of re zero s2 part 2. Now this is important for people who use MAl, AniList, and Kitsu, because according to those websites, part 2 of re zero s2 is separate, and therefore when we start tracking it, it will show that were on episode 14 out of 12 episodes, which really isn't bad, just weird, and after finish the anime, we will have to manually correct.

Also last part, maybe the source for anime should be changed from myanimlist to kitsu, since mal has a lot of outdated stuff in it.
