### ISSUE TITLE
Not scraping shows torrents from Nyaa

### ISSUE THREAD

**Issue by sathish804** [SwagOtaku/plugin.video.kaito#38]
Hi,

I was trying to watch Naruto Shippuden in Kaito. I see in Nyaa 2 torrents which are already cached in Real debrid but Kaito not scraping from Nyaa to find these torrents. 
![Screenshot_20210117-225900](https://user-images.githubusercontent.com/14090242/104857325-ecfc2700-5917-11eb-9fcc-71171970dac5.jpg)

**Comment by SwagOtaku** [comment]
@sathish804 fixed in version 0.0.8

**Comment by sathish804** [comment]
> @sathish804 fixed in version 0.0.8

Thank You!! Will check it and let you know!! Could you please let us know if you have Kaito addon for Kodi 19?

**Comment by sathish804** [comment]
@SwagOtaku Checked it and its scraping the sources from Nyaa now. Thank you.

![Screenshot_20210126-125929](https://user-images.githubusercontent.com/14090242/105842499-9311f600-5fd6-11eb-89d1-10420d30d377.jpg)
