### ISSUE TITLE
any other way to copy the MAL link?

### ISSUE THREAD

**Issue by simpsil** [SwagOtaku/plugin.video.kaito#44]
the kodi apps dont work on my phone where i can copy the code and kodi is on a android tv box

**Comment by DaisyF8** [comment]
(from memory, but I describe how you can input a string you have on your pc or phone into Kodi)

Use Chrome on you pc to authorize. Install Kassi from the Chrome Web store. Kassi is a remote for Kodi, you need to enter IP and Port (look in Kodi on your Android TV Box).  You can copy text on your pc, and paste it in Kodi.  You get a fillbox on your pc to type or paste in.

Same for Yatse (IP and port) to connect to Kodi on your Android TV Box.  You can also paste with a fillbox.

**Comment by DaisyF8** [comment]
Did it work?

**Comment by simpsil** [comment]
> Did it work?

yes there was an option on kodi that didnt let me use kassi its all good now :)
