### ISSUE TITLE
[Bug and Help] Search Engine Configeration.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [SwagOtaku/plugin.video.kaito#46]
Hi, im sorry for making this an issue but i need help configuring the search engine for Auramod or Artic Zephyr 2. Im making a menu for your addons and its really amazing and i love it but im having trouble customizing the search path for the search engine. 
I looked in this github post on how the search engine works and what examples it has and im trying to use this addon with it: https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36

Here is what the menu for your addon would look like and it is the best. 
![image](https://user-images.githubusercontent.com/62456796/107838007-c217be00-6d71-11eb-9511-2862f56819ba.png)
Now for the bug i noticed that the ratings are not working and that's about it. Its not really important to fix but i just thought i should show you this in case it is a bug.

If you could help me on what path to use to make the search engine work for this skin, that would help me out alot and it will complete my all in one media interface. Again, thank you so much for making this amazing add-on.

**Comment by Goldenfreddy0703** [comment]
Edit: Someone did help me figure it out by using this: plugin://plugin.video.kaito/search/
The only problem with this is that you have to add a /1 at the end of each anime title so i still need to try to find a way to search the anime title without putting a /1 at the end.
plugin://plugin.video.kaito/search/(animetitle)/1

**Comment by DaisyF8** [comment]
Couldn't find a solution either. I don't use the skins search anymore but sidenite a lot of other addons don't mention the search-string anymore...

For @swagotaku : This is the searchsyntax the skin expects. The search-string gets added to tge end.

Twitch

Streams
plugin://plugin.video.twitch/?content=streams&mode=search_results&index=0&query=

Channels
plugin://plugin.video.twitch/?content=channels&mode=search_results&index=0&query=

Games
plugin://plugin.video.twitch/?content=games&mode=search_results&index=0&query=

**Comment by unkn0wn234** [comment]
Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:


<property name="widgetPath" tag="property" attribute="name|list" value="DefaultSearch-Anime">plugin://plugin.video.kaito/search/</property>
<property name="widgetPath2" tag="property" attribute="name|list" value="DefaultSearch-Anime">/1</property>

Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).

^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.

**Comment by unkn0wn234** [comment]
Also, how did you get the clearlogos to show up?

**Comment by Goldenfreddy0703** [comment]
Hey i just wanna say, thank you for the big help and im sorry i was taking a break from the search path, the clearlogos are from The Auramod Mod Skin where the skin itself basically looks up the clearlogos itself thru api keys and stuff. I think Auramod has this function where you can fill out clearlogos which is why you can see them.

**Comment by Liquidrag** [comment]
> Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:
> 
> plugin://plugin.video.kaito/search/
> /1
> 
> Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).
> 
> ^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.

Could you do screenshots for us? I'm a bit lost.

**Comment by unkn0wn234** [comment]
> > Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:
> > plugin://plugin.video.kaito/search/
> > /1
> > Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).
> > ^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.
> 
> Could you do screenshots for us? I'm a bit lost.

Sorry I havent touched Auramod and Arctic Horizon in a while I use a skin that doesnt have custom search engines so cant help much until I one day decide to go back

**Comment by Liquidrag** [comment]
> > > Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:
> > > plugin://plugin.video.kaito/search/
> > > /1
> > > Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).
> > > ^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.
> > 
> > 
> > Could you do screenshots for us? I'm a bit lost.
> 
> Sorry I havent touched Auramod and Arctic Horizon in a while I use a skin that doesnt have custom search engines so cant help much until I one day decide to go back

All good. Thanks anyways.

**Comment by icpryde** [comment]
> > > > Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:
> > > > plugin://plugin.video.kaito/search/
> > > > /1
> > > > Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).
> > > > ^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.
> > > 
> > > 
> > > Could you do screenshots for us? I'm a bit lost.
> > 
> > 
> > Sorry I havent touched Auramod and Arctic Horizon in a while I use a skin that doesnt have custom search engines so cant help much until I one day decide to go back
> 
> All good. Thanks anyways.

Hey did you find a way to get the search strings to work in AH or AZ? This would be amazing to have added!

I know for Seren I use these for TV shows and Movies

plugin://plugin.video.seren/?action=moviesSearchResults&actionArgs=

plugin://plugin.video.seren/?action=showsSearchResults&actionArgs=

I just wish this would work for Kaito too.

**Comment by icpryde** [comment]
> Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:
> 
> plugin://plugin.video.kaito/search/
> /1
> 
> Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).
> 
> ^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.

@SwagOtaku anyway is it possible to add this to kaito so we can use search strings ?

**Comment by Goldenfreddy0703** [comment]
> > Go into the skins files, and then into the shortcuts folder. Look for the template.xml and add this right below the property that adds the default search for TMDb-People:
> > 
> > plugin://plugin.video.kaito/search/
> > /1
> > 
> > Then in the search list, create a new search for Anime and set the action to DefaultSearch-Anime (manually typed unless you want to code it into the overrides.xml, look at TMDb People for how).
> > 
> > ^the above is for Arctic Horizon, for Auramod I had to change the WidgetPath and WidgetPath2 to path and path2 accordingly, when you edit the xml, just match the formatting.
> 
> @SwagOtaku anyway is it possible to add this to kaito so we can use search strings 

@icpryde , the developer already added this in Auramod cause I already asked him to do that but on Artic Horizon, you may need to ask jurialmunkey about adding the search string. 


https://github.com/SerpentDrago/skin.auramod/issues/96

**Comment by Goldenfreddy0703** [comment]
Actually @icpryde I'm sorry but I think I misread. What are you trying to ask by anychance so I could understand what your asking SwagOtaku?
