### ISSUE TITLE
Kodi 19 (Matrix) Support

### ISSUE THREAD

**Issue by jason-oliveira** [SwagOtaku/plugin.video.kaito#47]
Seems Kodi has moved everything to Python3 in version 19, and all the AddOns need to be updated accordingly. Please let us know where we can send Pocky.

**Comment by unkn0wn234** [comment]
https://github.com/SwagOtaku/plugin.video.kaito/issues/37

**Comment by SwagOtaku** [comment]
Updated the repo with matrix compatibility
