### ISSUE TITLE
When Finishing a series and Playing Next Dialog popup issue

### ISSUE THREAD

**Issue by icpryde** [SwagOtaku/plugin.video.kaito#5]
I noticed 2 things when I completed a series, the Playing Next Dialog feature when it plays the next episode will still show up on the final episode and play a random episode. In this case I was on episode 12 which was the final episode and then it suggested to play episode 7 because their was no more episodes.

Another thing I noticed is the show will remain in my "currently watching" list but be listed as 12/12 so showing its completed but not disappearing until I physically went to AniList to mark it as "completed".

Maybe a way to let me give a rating when I complete a series?

This was with AniList....not sure if this problem occurs with Kitsu or MAL.

**Comment by SwagOtaku** [comment]
>the Next Up feature when it plays the next episode will still show up on the final episode and play a random episode. In this case I was on episode 12 which was the final episode and then it suggested to play episode 7 because their was no more episodes.

I haven't encountered the next episode issue on the final episode, ran some tests with no issues. Have you encountered this issue more than once?

>I noticed is the show will remain in my "currently watching" list but be listed as 12/12 so showing its completed but not disappearing until I physically went to AniList to mark it as "completed".
Maybe a way to let me give a rating when I complete a series?

As of right now that's how it works (since AniList and MAL doesn't auto mark it completed unlike Kitsu which does) , but planning on adding a better to way to handle this.

**Comment by icpryde** [comment]
@SwagOtaku I've only encountered it watching a small anime called Somali and the Forest Spirit. It was only 12 episodes so as soon as the final episode was about to be finished the dialog window pops up saying "play episode 7" which obviously is incorrect as no episodes exist past 12.

It's a super minor issue but I am almost done another show so once it's done I;ll check to see if it does the same thing again or not.

I know you already said you are making a tweak to better handle completed seasons with AniList so that will take care of the 2nd issue then.


edit: _also fixed the titling as it gets confusing calling it "Up Next" and "Next Up" as those are 2 seperate things and now the community is just calling Up Next as " Playing Next Dialog pop up" or "smart play popup"._

**Comment by icpryde** [comment]
@SwagOtaku I finished another series and same issue as before, this time I finished the last episode which was total 64 episodes on the final episode the pop up window displays asking to play an older episode like episode 53.

Maybe this is specifically an AniList issue?

**Comment by icpryde** [comment]
I'm going to close this to start a new request with updated information.
