### ISSUE TITLE
Can we please get a way to disable any dubbed anime sources?

### ISSUE THREAD

**Issue by 9crack** [SwagOtaku/plugin.video.kaito#52]
Can we please get a way to disable any dubbed anime? Have tried by changing language preference to Japanese but it doesn't work, if I disable autoplay there are enough subbed sources but it defaults to dubbed, this would be a great feature for an already great addon, thanks for your work.

**Comment by Prometheusx-git** [comment]
Under Sort&Filter you can Hide dub sources.

**Comment by 9crack** [comment]
Well thank you so much, I never saw the option, awesome job on this addon.
