### ISSUE TITLE
MAL authorize  = Rasp PI 2 crash

### ISSUE THREAD

**Issue by Kodionpi** [SwagOtaku/plugin.video.kaito#6]
Hello, thanks for your work! I run Kodi 18.8 (Libreelec 9.2.4) on Raspberry Pi 2 Model B (ARM7). When I try to authorize my MAL Account --> having copied the URL --> in the moment i click on "authorize" --> PI/Libreelec freezes --> PI/Libreelec crashes & reboots. -sry for my english. On Windows everything runs perfectly fine!

**Comment by DaisyF8** [comment]
On my Shield I didn't have crashes, but I had to authorize RealDebrid and Premiumize two or three times before the registration showed up in the settings.

Do you authorize on your phone, or a laptop, or... ?

**Comment by khalid410** [comment]
Can confirm this happens on boxes running Coreelec 9.2.4. Freezes when I click authorize for MAL or Anilist.

**Comment by SwagOtaku** [comment]
i adjusted the authorization for MAL and Anilist for linux in new update (version 0.0.5). Let me know if it fixes the issue

**Comment by Kodionpi** [comment]
@DaisyF8 I used the web interface on my browser (Windows PC) to copy the url. 

@SwagOtaku I installed update 0.0.5 and now the authorization worked! Thank you! 

How will "new" user know where to get the url? -because the link to get the right MAL Url does not appear anymore when authorization is clicked. This one "https://armkai.vercel.app/api/mal"

**Comment by SwagOtaku** [comment]
@Kodionpi added authorization instruction dialog for linux os in version 0.0.6
