### ISSUE TITLE
Kodi matrix problem with kaito v0.0.9

### ISSUE THREAD

**Issue by tieu1991** [SwagOtaku/plugin.video.kaito#61]
The last update 0.0.9 won't install on kodi matrix because it try to import xbmc.python v2.26.0

**Comment by SwagOtaku** [comment]
I haven't updated the repo with matrix compatibility update yet, need to make some changes. I will update in a few days when I'm done with making the changes.

**Comment by SwagOtaku** [comment]
Updated the repo with matrix compatibility
