### ISSUE TITLE
Libreelec matrix download and subtitle issues

### ISSUE THREAD

**Issue by dunnhole** [SwagOtaku/plugin.video.kaito#62]
Just did a new build and have libreElec's beta matrix on a pi4.  Tried installing from repo and no video addons are available to install, can not install addon from there.  Tried the fork in the pull requests section and it installs and pulls links and plays but I can not get subtitles to work.

**Comment by SwagOtaku** [comment]
I haven't updated the repo with matrix compatibility update yet, need to make some changes. I will update in a few days when I'm done with making the changes.
