### ISSUE TITLE
No video add-ons when accessing SwagOtaku Repo to install

### ISSUE THREAD

**Issue by givingthisago** [SwagOtaku/plugin.video.kaito#64]
Added Source  https://swagotaku.github.io/repo/

Named SwagOtaku

Go to install from repository

Click on SwagOtaku Repo

Only see "Add-on Repository" listed

No Video add-ons in the repo

Using Kodi 19

**Comment by SwagOtaku** [comment]
I haven't updated the repo with matrix compatibility update yet, need to make some changes. I will update in a few days when I'm done with making the changes.

**Comment by SwagOtaku** [comment]
Updated the repo with matrix compatibility
