### ISSUE TITLE
Anilist problem

### ISSUE THREAD

**Issue by DaisyF8** [SwagOtaku/plugin.video.kaito#67]
Both on Matrix and Leia I can't auth with Anilist?

Message is "Login : Incorrect username or password", 
but in settings Username and Token get filled in regardless which is strange.

The verification in Kaito asks for username and token. Do you use username or do you use email-adres ? I've tried both, neither works. Also reset to defaults, uninstalled with delete settings, and changed password on Anilist.

Every time I do https://armkai.vercel.app/api/anilist I get a different token (which is normal I guess).

Anyone else experience this ?

**Comment by Gujal00** [comment]
Can you check with the zip in this post https://github.com/SwagOtaku/plugin.video.kaito/pull/57#issuecomment-821942447 I tested with MAL on that and it worked fine
You can use that zip on both Leia and Matrix

**Comment by DaisyF8** [comment]
I just tested on Leia and Matrix. Still problem, I think probably something on my end.

Before I installed your file I uninstalled the existing Kaito and also deleted settings.

When I click authorize I get an error. At the moment I don't even see the message that displays the url.

Leia https://paste.kodi.tv/qoqudoraqe

Matrix https://paste.kodi.tv/kobekelami

**Comment by Gujal00** [comment]
On your Kodi Leia, you are missing a dependency `UserWarning: The soupsieve package is not installed`.
Install this from zip
```
http://mirrors.kodi.tv/addons/leia/script.module.soupsieve/script.module.soupsieve-1.9.6+leia.1.zip
```
On Matrix even MAL is having issue in your log that is strange as it works on my Windows and CoreElec test machines. I will test on Android to see if any issue there

**Comment by DaisyF8** [comment]
Result for Leia sofar : a new message pops up, see log.  This after I uninstalled previous install, with deletion of settings, and I checked in addons/ and userdata/addon_data that there was no folder remaining (just to be sure).

http://paste.kodi.tv/iqomahatoc

I also found a reference to the soupsieve issue https://github.com/Sandmann79/xbmc/issues/352.  Seems  it could be related to downgrading Beautifulsoup to keep Kaito working.

**Comment by DaisyF8** [comment]
For Matrix : since that Mal error was so weird I uninstalled and checked as described for Leia.  The Mal error is gone. But I now get the same error as in Leia when I "click to authorize".

http://paste.kodi.tv/arofiforak

**Comment by Gujal00** [comment]
> 
> 
> Result for Leia sofar : a new message pops up, see log. This after I uninstalled previous install, with deletion of settings, and I checked in addons/ and userdata/addon_data that there was no folder remaining (just to be sure).
> 
> http://paste.kodi.tv/iqomahatoc
> 
> I also found references to the soupsieve issue here [Sandmann79/xbmc#352](https://github.com/Sandmann79/xbmc/issues/352) and [here](https://www.reddit.com/r/Addons4Kodi/comments/mlt0bj/seren_update_error_dependency_on_modulescript/) . Seems it is related to downgrading Beautifulsoup to keep Kaito working and then BS not recognizing Soupsieve anymore.

do not downgrade bs4, just install the zip that i linked above, it works fine as I use that with Leia perfectly fine

**Comment by Gujal00** [comment]
> 
> 
> For Matrix : since that Mal error was so weird I uninstalled and checked as described for Leia. The Mal error is gone. But I now get the same error as in Leia when I "click to authorize" for anilist.
> 
> http://paste.kodi.tv/arofiforak
> 
> And the same Kodi session, after "click to authorize" but for MAL,
> 
> http://paste.kodi.tv/umosukiwex
> 
> gives the same error.

Looks like skin issue, test with Estuary skin please

**Comment by DaisyF8** [comment]
Also on Estuary, the errors stay on Matrix and Leia. Very strange. As soon as I push "click to authorize"

Matrix http://paste.kodi.tv/wupepivobe

Leia http://paste.kodi.tv/xonucuzaho

**Comment by Gujal00** [comment]
Okay can you please download the kaito 0.1.0 zip again from that link and install and test. I may have found the issue, i replaced the zip in my github, didnt change the version number

**Comment by DaisyF8** [comment]
Yesss !

That fixed it both for Matrix and Leia :)

Nice Gujal. Thanks so much.

**Comment by Gujal00** [comment]
yeah, i think so, as it was working fine for me in Windows and Coreelec
Anyway, the modified code works on Android, WIndows and Coreelec, so should be fine

**Comment by DaisyF8** [comment]
Nice :+1: 

Just out of interest, do you push this to Swagotaku-repo, so he can update also ?

**Comment by Gujal00** [comment]
It is part of the PR which @swagotaku has deferred for now as he doesnt want to use six and kodisix. He wants the PR left open for now for people to test as an alternative

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DaisyF8** [comment]
Well thx for being a dev.
