### ISSUE TITLE
[Request] TMDB Helper Player support?

### ISSUE THREAD

**Issue by mathu204** [SwagOtaku/plugin.video.kaito#7]
I understand if this cant be implemented as its been explained to me before, however if it is possible to implement a TMDB player for this it would be so great.

**Comment by icpryde** [comment]
@mathu204 can you elaborate further what it is you are asking for exactly?

**Comment by mathu204** [comment]
> @mathu204 can you elaborate further what it is you are asking for exactly?

Yes, so basically I assume you know what TMDB Helper addon is in Kodi. It’s a movie and show viewer addon that has players, so let’s say I click an episode of The Simpson’s. I can use a player in TMdB Helper addon that will, when I click an episode of Simpson’s will play it in my addon of choice such as Disney +. So I want to be able to play an episode of anime like re Zero inside tmdb helper and make it use Kaito as the player. Since the players I have for addons like Disney, seren, etc won’t work as well for anime as kaito does. I currently use Fen with cloud scraping and it’s great but if I could make it use Kaito it would be great

**Comment by DaisyF8** [comment]
These are all listed in Github a4k_openproject/json.openplayers

**Comment by mathu204** [comment]
> These are all listed in Github a4k_openproject/json.openplayers

I don’t see it there, or are you saying I should open a request there

**Comment by DaisyF8** [comment]
Yeah, there isn't one yet (and such a player is very difficult to write if I understand the trouble with naming conventions for anime seasons and show names correctly).

I just wanted to illustrate the player system.

**Comment by DaisyF8** [comment]
This Issue should be marked SOLVED
