### ISSUE TITLE
[Request] Cloud scraping

### ISSUE THREAD

**Issue by mathu204** [SwagOtaku/plugin.video.kaito#8]
This was supposed to be a feature in Hummingbird, if Kaito could scrape for content in the cloud of whichever debrid service we integrate it would be a game changer. Because theres just something about seeing the metadata and marking it as watched when playing episodes vs just playing it from my files; atleast for me lol. Anyways thanks for making this great adddon btw!

**Comment by SwagOtaku** [comment]
@mathu204 added cloud scraping in version 0.0.6

**Comment by mathu204** [comment]
> @mathu204 added cloud scraping in version 0.0.6

Thank you !
