### ISSUE TITLE
Nyaa scrapper only working when selecting rescrape. 

### ISSUE THREAD

**Issue by khalid410** [SwagOtaku/plugin.video.kaito#9]
Addon seems to successfully scrape Nyaa season packs only when I select rescrape from the context menu.
Trying to directly play an episode only brings up individual episode torrents and season packs on a handful of shows.

**Comment by icpryde** [comment]
can you provide a log file so swag can see what is happening.

**Comment by SwagOtaku** [comment]
@khalid410 improved season pack scraping in version 0.0.6
