### ISSUE TITLE
Problem with searching titles

### ISSUE THREAD

**Issue by dpetka2001** [SwagOtaku/plugin.video.kaito#91]
Excuse me if i'm wrong about this, but from what i noticed with my limited knowledge, i think that kaito takes the titles from Anilist/Anichart and searches accordingly to find available episodes. But many groups release episodes with naming according to MyAnimeList, which sometimes might be different from Anilist. For example Kimetsu no Yaiba 2nd season is referred in Anilist as "Kimetsu no Yaiba 2" and in Myanimelist as "Kimetsu no Yaiba: Mugen Ressha-hen". As such at the moment at least in the current version of Kaito it doesn't produce any results for the episodes. But i see that Anilist references in the synonyms the title from Myanimelist as well, so i was wandering if in the process of searching for episodes Kaito could consider the synonyms titles available as well. If i'm wrong somewhere please be free to correct my assumptions.

**Comment by SwagOtaku** [comment]
The addon uses the synonyms as well for searching. For some reason anilist has decided to combine Kimetsu no Yaiba: Mugen Ressha-hen and Kimetsu no Yaiba Season 2 into one entry (read this for more info https://anilist.co/forum/thread/43538). 

I will look into this and let you know what I find.

**Comment by Goldenfreddy0703** [comment]
Holy crap your back, its so good to see you @SwagOtaku. Hope your addon gets updated soon.

**Comment by dpetka2001** [comment]
Thank you so much for your response and maybe while you're looking at the aforementioned issue, you could also look into animes that have 2 cours (i.e Mushoku Tensei and Mushoku Tensei Part 2 or even 86 and 86 Part 2). The Parts 2 start the numbering of episodes immediately where the Part 1 left off and many groups in Nyaa release the episodes with names assuming that this is a continuation of Part 1. So instead of Mushoku Tensei Part 2 S02E01 they go with Mushoku Tensei S01E13 as continuation from the first season. Of course I have no idea how difficult this could be, so it's up to you whether it can be fixed or not. Just thought I should also let you know of this. Maybe you could find a way to differentiate between animes with Part 2 and animes with actual Season 2, so that the plugin would know what to expect in the title names during the search process. Thank you in advance for your hard work for this addon.
